baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Blitz Reduced Test Case'
primary: true
siteGroup: a58a422e-c7eb-4639-a6de-377c1f401ee2 # Blitz Reduced Test Case
sortOrder: 1
