fieldLayouts:
  80c5faf7-8d12-452f-b79e-f632c825f504:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 5ce997c1-6bb7-445d-8bba-0702482098b8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6c71a32e-6d26-446f-ab7e-0cec42797e42
        userCondition: null
fs: localFilesystem
handle: local
name: Local
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
